version: 2
jobs:
  build-and-test:
  macos:
    xcode: "10.1.0"
  working_directory: /Volumes/FusionHD/legentis/knife-in-pocket/
  environment:
    FL_OUTPUT_DIR: output
    FASTLANE_LANE: test
  shell: /bin/bash --login -o pipefail
  steps:
    - checkout
    - run: bundle install
    - run:
      name: Fastlane
      command: bundle exec fastlane $FASTLANE_LANE
    - store_artifacts:
      path: /Volumes/FusionHD/legentis/knife-in-pocket/
    - store_test_results:
      path: /Volumes/FusionHD/legentis/knife-in-pocket/

